// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VotesGet.Helpers;

#nullable disable

namespace VotesGet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VotesGet.Model.Vote", b =>
                {
                    b.Property<long>("reviewId")
                        .HasPrecision(10)
                        .HasColumnType("bigint")
                        .HasColumnName("ReviewID");

                    b.Property<long>("userId")
                        .HasPrecision(10)
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<string>("vote")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Vote");

                    b.HasKey("reviewId", "userId")
                        .HasName("PK_VOTES");

                    b.HasIndex(new[] { "reviewId" }, "IDX_REVIEWID");

                    b.HasIndex(new[] { "userId" }, "IDX_USERID");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
