openapi: 3.0.1
info:
  title: amceSpanish
  description: API Definition of amceSpanish
  version: 1.0.0
servers:
- url: http://localhost:8290/spanish
paths:
  /quantityReviews:
    get:
      responses:
        default:
          description: Default response
  /VotesByReviewsByUserId:
    get:
      responses:
        default:
          description: Default response
  /reviewsMoreUpvote:
    get:
      responses:
        default:
          description: Default response
  /reviews/upvote/percentage:
    get:
      responses:
        default:
          description: Default response
  /VotesByUserId:
    get:
      responses:
        default:
          description: Default response
  /EvaluteQuantityUpDownVotes:
    get:
      responses:
        default:
          description: Default response
  /VotesByReviewId:
    get:
      responses:
        default:
          description: Default response
